### ISSUE TITLE
Network Limitations

### ISSUE THREAD

**Issue by apertix** [jackharrhy/bitbot-vb#2]
I believe the fact that every modification to the position of the joystick would send new instructions to the Phidget. I had an issue in my code where it was sending too many calls to update the speed of the motors and was resulting in a gigantic lag because of the crappy wireless receiver. Where you guys have changed over to using the router I believe that you didn't experience this effect, therefore didn't account for it in your code.

**Comment by jackharrhy** [comment]
The method I use for updating the PhidetSBC is by having a sub that loops every x amount of milliseconds (by default 200ms), and the joystick input is polled when it is needed, so I don't think that's the bottleneck.
The code ran _perfectly_ when the video camera was not in use, but once the camera was put in use , plenty of packet loss even on the lowest setting; the video feed itself wasn't that bad but any control from my program took about _ten seconds_ to update.

**Comment by apertix** [comment]
I wish he wasn't so cheap lmao and bought decent equipment. David was telling me that you guys were thinking about swapping out the small LinkSys router for each Robot so they wouldn't have to use that crappy USB receiver? Also what do you mean by it polls the joystick when needed? From what I read it gets the input from the joystick and sets that to the velocity every 200ms.

**Comment by jackharrhy** [comment]
David was looking into the routers yes; we only have about four of them including out own, and the other three don't seem responsive by conventional means.  To fix the ethernet ports on ours we had to connect to it via wifi and reset it via the web interface since the physical reset switch doesn't do the full job.
The others are either broken (they are decommissioned school network routers) or not broadcasting publicly.
Its a very long shot, but maybe a second wireless card, or even Bluetooth would work?, although that would require some behind the scenes SSHing into the PhidgetSBC to hack together a solution, without a viable internet connection as well. 

robotiks wit spurl™
¯\_(ツ)_/¯
